name: chervyak
version: 0.1.0.0
github: "githubuser/chervyak"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/chervyak

dependencies:
  - base >= 4.7 && < 5
  - gloss
  - random

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  

executables:
  chervyak-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chervyak

tests:
  chervyak-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chervyak
