name:                chervyak2
version:             0.1.0.0
github:              "githubuser/chervyak2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chervyak2#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random
- parsec >= 3.1.11 && < 4
- servant
- servant-client
- servant-server
- aeson >= 1.1
- mtl
- HDBC >=2.4 && <3.0
- HDBC-sqlite3

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  chervyak2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chervyak2

tests:
  chervyak2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chervyak2
